### PR TITLE
improving dependencies and removing deprecations/old plugins

### PR DESCRIPTION
**Pull request by javabeanz**

### CODE REVIEW

**Comment by fjakop** [comment]
thanks for the work, but please mind 2 things
1. please do not change the formatting
2. as long as this plugin is _maybe_ supported by adrena  (som licensing issues pending) and it's groupId is not changed, please keep version with tolina-classifier

**Comment by javabeanz** [comment]
what licensing issues exist then ? i am preparing migration to maven 3 api with annotations. maybe we should fork and new groupid ?

**Comment by fjakop** [comment]
It is not clear whether the goal "macker-no-fork" is compatible with macker's GPL, since there are different understandings of "linking".

**Comment by javabeanz** [comment]
can we get a quick answer to that doubt ? maybe create a new impl from
scratch with same functionality ?
this license issue holds us back, which shouldnt be in open source.

**Comment by fjakop** [comment]
I don't think for a quick solution, because macker's developers seem to be rather unavailable. If you need a quick solution I think using your own fork would be best.
What do you mean with "which shouldnt be in open source"?

**Comment by javabeanz** [comment]
it shoundt be that developers are hindered by an unclarity in license
issues.

Somehow, I like the concept macker impements, but not the implementation;
it is rather buggy from my experience. So maybe a new impl would be the
best way then.

**Comment by wojtus** [comment]
you are right: developers should not be hindered. but the sad true is, that there are licence issues with the GPL licence - the GPL ist quite restrictive (the 'viral' aspect). this is good on the one hand, but bad on the other. 
a new implementation is allways welcome, but is a big amount of work. the backward compatibility shoud be kept in mind.

**Comment by javabeanz** [comment]
The author of Macker is ready to make his code BSD licened; is that ok with
you guys ? it was rather easy to reach him.

**Comment by wojtus** [comment]
It would be great to have macker under the BSD licence. Do you konw the way, he is going achive this?
Will he publish a new artifact version with changed licence to MavenCentral?

**Comment by javabeanz** [comment]
turns out jqassistant is much more advanced, no need to develop macker
further.

**Comment by wojtus** [comment]
we use macker since some years an it worked well in most of the use cases. but of course we noticed the staled development of the core of macker. potentially we will need to reevaluate this decision some day and check the pros&cons of a migration. 
thanks for the hint with the jqassistant. :)

**Pull request closed without merging**
